# Generated by Django 2.0 on 2019-02-11 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='编码')),
                ('designer', models.CharField(max_length=10, verbose_name='设计师')),
                ('label', models.CharField(blank=True, max_length=10, null=True, verbose_name='标签')),
                ('work', models.BooleanField(default=False, verbose_name='是否上架')),
                ('image', models.ImageField(default='goods_image/default.png', upload_to='goods_image', verbose_name='图片')),
                ('describe', models.TextField(verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
